"""Build planning records from source-bound readings. Does not run paper analysis."""
from pathlib import Path
import hashlib
import json
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parents[3]
OUT = Path(__file__).resolve().parent
CON = ROOT / 'quality_reports/argument_contracts/ivb-pa-refine/5375d3c27ac1'
ADJ = ROOT / 'quality_reports/adjudication/ivb-pa-refine/5375d3c27ac1'
ADJ.mkdir(parents=True, exist_ok=True)
now = datetime.now(timezone.utc).isoformat()
sha = lambda p: hashlib.sha256(Path(p).read_bytes()).hexdigest()
pdf = ROOT / 'ivb_paper_pa.pdf'
rmd = ROOT / 'ivb_paper_pa.Rmd'
assert sha(pdf) == '5375d3c27ac1b75ca7246f0e7483470d98a69cf129a853560ae84cfe107d447c'
assert sha(rmd) == '12493a67133f988c5e6a13933bf2b89c0d9880e96bae329248a207b3aeaf7b5e'

sections_raw = [
 ('Introduction','178-195; PDF pp.1-3','read_timing, turno reader-introduction','motivação e contribuição',['C01','C04'],['Não propõe estimador causal universal'],['Promete interação entre diagnóstico e baseline nas aplicações']),
 ('The Time-Varying Control Problem','196-207; PDF pp.3-4','read_simulations, turno reader-control-problem','problema, alvo e escopo',['C03','C04'],['Não resolve identificação geral de covariadas responsivas'],[]),
 ('DAGs, Timing, and Why Z_t Is Not Z_t-1','208-386; PDF pp.4-7','read_timing','relógio temporal e papéis causais',['C03'],['Lag não prova anterioridade; Y lag não fecha collider atual'],['Any responses e relógio de collider precisam conciliação local']),
 ('The Specification-Shift Diagnostic','387-502; PDF pp.8-12','read_diagnostic','álgebra, inferência e identificação',['C01','C02','C04','C06'],['Não é novo estimador; sem IC aplicado; FE têm limites'],['Moved sugere substituição; qualificações sobre FE e mediação estão mais completas nas derivações']),
 ('Benchmarking Dynamic Specifications for the CET','503-643; PDF pp.12-18','read_simulations','DGPs e workflow',['C05','C04'],['Simulações não generalizam fora do grid'],['ADL denota RHS diferentes; cobertura de long não é cobertura de Delta; isola é claim mais forte que a comparação']),
 ('Applications','644-823; PDF pp.19-21','read_applications','diagnósticos empíricos e ambiguidade',['C07'],['Não estima prevalência; não demonstra diretamente CET; sem IC pareado'],['14 candidatos, seis estudos e controles adicionais não são exibidos em universo único']),
 ('Conclusion','824-836; PDF p.21','read_applications, turno conclusion','síntese e fronteiras',['C01','C04','C08'],['Sem resultados SDiD, fatores, efeitos acumulados ou links não lineares'],[]),
]
claims = [
 ('C01','O deslocamento entre regressões lineares aninhadas tem identidade exata FWL; sua interpretação como IVB exige identificação causal.','identidade amostral e interpretação causal condicional','Rmd 184-190,389-420,826','Equações curto/longo e auxiliar; Proposição 1','OLS sem pesos, posto completo, amostra e regressoras comuns'),
 ('C02','O shift conjunto é único; incrementos sequenciais dependem da ordem e leave-one-out não é soma aditiva.','álgebra condicional','Rmd 408-422; derivations/multivariate_specification_shift.Rmd','Identidade vetorial, definições e prova por FWL','Especificações lineares aninhadas; alocação não causal'),
 ('C03','O relógio substantivo determina papéis candidatos; lag não torna controle admissível automaticamente.','causal condicional a DAG e relógio','Rmd 214-275,279,315,385','Definição CET, tabelas1-2 e figuras1-2','CET atual; relógios de mediador e collider diferentes'),
 ('C04','ADL+FE é baseline condicional para CET linear homogêneo com história suficiente e condições de identificação e estimação.','resultado populacional condicional','Rmd 457-501; derivations/adl_cet_identification_conditions.Rmd:63-73','Média potencial, prova FWL, suporte, tabela3','Intercambialidade completa nas derivações; não garante within sem viés em T finito'),
 ('C05','Os modelos com estados relevantes têm menor viés em DGPs exibidos; o baseline falha com confounding omitido.','evidência numérica delimitada','Rmd 551-642; figuras4-5; tabela6','Outputs existentes e parâmetros/captions','DGPs testados; cobertura0.700 é de long para CET; não é calibração de IC do shift'),
 ('C06','Incerteza do shift deve preservar covariância entre estimadores; procedimentos são propostos, não calibrados nas aplicações.','proposta inferencial de escopo restrito','Rmd 424-438; derivations/specification_shift_uncertainty.Rmd:260-264','Variância da diferença, script pareado, nota de trabalho não executado','Um controle, OLS, amostra completa comum, cluster por unidade; limites reconhecidos na nota'),
 ('C07','Aplicações são diagnósticos descritivos com timing ambíguo de contrastes defasado/prospectivo.','evidência descritiva intencional','Rmd 646-650,732-736,822','Leipziger e Rogowski; tabelas7-8','14 candidatos em seis estudos; duas aplicações, três controles extras de Rogowski; sem CET direto ou IC do shift'),
 ('C08','A contribuição desenvolvida se limita a TSCS linear e uso condicional do diagnóstico.','escopo','Rmd 444,828-832','Conclusão e declaração de extensões futuras','Sem resultados para SDiD, fatores, regimes, links não lineares ou efeitos acumulados'),
]
reconciliations = [
 ('A versão afirma identificação universal ou condicional?','Condicional: Rmd190,457-501,828 e nota de identificação. Frases locais mais fortes continuam registradas como inconsistências, sem atribuir claim universal ao paper.'),
 ('Moved significa uma inclusão aninhada?','A intenção não é inferida. O contrato registra a identidade válida para adição e a frase operacional451 compatível com substituição, não coberta por essa identidade. É um defeito/ambiguidade textual localizado que o plano deve resolver, não prova de erro no teorema.'),
 ('Intercambialidade com FE está ausente de todo o argumento?','Não: explicitada na nota63-73; omitida na formulação abreviada Rmd465. A crítica incide na consistência de exposição e na rechecagem da cadeia afetada.'),
 ('O paper identifica efeito direto somente pelo DAG?','Seção3,315 exige hipóteses de mediação; Rmd441 comprime inadequadamente essa condição. O contrato conserva ambos os localizadores e não atribui uma tese incondicional global.'),
 ('Cobertura0.700 é para Delta?','Não. metrics.R:57 usa covered_long; simulation.R:70-111 compara ao beta_true, com beta_cet como alvo. Não é IC pareado de Delta.'),
 ('As cinco linhas são subset simples dos14 candidatos?','Não. Rmd141-150 seleciona só GDP em Rogowski; sua tabela inclui três controles adicionais. O contrato separa estudo, candidato selecionado e comparação adicional.'),
 ('Restam dúvidas que mudem a descrição do argumento?','Não para o escopo de planejar revisão: as tensões foram explicitamente preservadas como propriedades textuais, não eliminadas ou resolvidas por atribuição de intenção. Validade científica e decisões de desenho permanecem para os gates futuros.'),
]
support = [rmd, ROOT/'derivations/adl_cet_identification_conditions.Rmd', ROOT/'derivations/multivariate_specification_shift.Rmd', ROOT/'derivations/specification_shift_uncertainty.Rmd', ROOT/'derivations/shift_allocation_correlated_controls.Rmd']
contract = {
 'schema_version':'1.0','contract_id':'ivb-pa-refine:5375d3c27ac1:round1','profile':'general',
 'source':{'reviewed_artifact':str(pdf),'sha256':sha(pdf),'editable_sources':[{'path':str(p),'sha256':sha(p)} for p in support]},
 'document':{'title':'From Specification Shifts to Included Variable Bias in Dynamic Panels: A Diagnostic for Time-Varying Controls and a Benchmark for the Contemporaneous Treatment Effect','language':'en','format':'pdf','word_count':len((OUT/'evidence/manuscript_pdf_text.txt').read_text().split()),'page_count':22,'substantive_sections':7},
 'section_map':[{'section_id':f'S{i:02}','title':s[0],'locator':'ivb_paper_pa.Rmd:'+s[1],'reader_id':s[2],'function':s[3],'claims':s[4],'evidence':[f'section_reads/section_{i:02}_*.md'],'non_claims':s[5],'ambiguities':s[6]} for i,s in enumerate(sections_raw,1)],
 'synthesis':{'thesis':'Quantificar mudanças de especificação com identidade linear e interpretar causalmente somente sob estimando, timing e identificação defendidos.','research_question':'Quanto um controle responsivo ao tratamento move o coeficiente e quando uma especificação dinâmica pode servir de comparação para o CET?','contribution':'O manuscrito reivindica organização diagnóstica da identidade e um baseline ADL+FE condicional; sua distinção da literatura é questão para revisão, não certificada pelo contrato.','claim_type':'matemático descritivo, causal condicional e simulado delimitado','core_claims':[{'claim_id':c[0],'text':c[1],'strength':c[2]} for c in claims],'evidence_map':[{'claim_id':c[0],'source_locator':c[3],'evidence':c[4],'scope':c[5]} for c in claims],'scope_conditions':[c[5] for c in claims],'non_claims':['Não cria novo estimador causal universal.','Não infere causalidade ou papel do controle apenas de theta, pi ou Delta.','Não garante lag admissível ou história suficiente pelo índice temporal.','Não oferece ICs pareados nas aplicações atuais.','Não resolve efeitos de regimes, SDiD, fatores ou confounding contemporâneo omitido.','Não interpreta seis estudos como amostra representativa.'],'terminology':[{'preferred':'specification shift','avoid':['causal bias sem identificação'],'reason':'Contraste de projeções não é automaticamente viés causal.'},{'preferred':'conditional ADL+FE baseline','avoid':['safe model','universal estimator'],'reason':'CET, timing, história e condições são necessários.'},{'preferred':'intervalo Monte Carlo da média do viés','avoid':['IC do CET','IC do shift'],'reason':'Objetos de incerteza distintos.'}],'ambiguities':[],'profile_fields':{'methodological_objects':['CET','projeção populacional','coeficiente amostral','shift','viés','intervalo'],'empirical_adapter':'Aplicações são ilustrações heterogêneas; não há tratamento/outcome único.','formal_adapter':'Não é jogo estratégico; perfil general cobre teoremas e condições estatísticas.'},'not_applicable':{'empirical_profile':'Paper metodológico, aplicações não constituem desenho empírico único.','formal_game_fields':'Não há jogadores, estratégias ou equilíbrio.'}},
 'reconciliation':{'questions':[r[0] for r in reconciliations],'responses':[r[1] for r in reconciliations],'unresolved':[]},
 'gate':{'status':'PASS','round':1,'checked_at':now,'checks':{k:True for k in ['coverage','anchors','scope','nonclaims','preferred_specification','ambiguities','source_hash']},'reasons':['Sete seções cobertas por registros próprios; quatro agentes reutilizados em turnos para seções curtas devido ao limite do ambiente. Não são sete contextos independentes.','Síntese macro feita pelo orquestrador após leitura integral; tensões textuais preservadas na seção e no log de reconciliação.','PASS de fidelidade para planejar revisão; não aprova novidade, validade das provas ou publicação.']},
}
CON.mkdir(parents=True, exist_ok=True)
dump=lambda p,o: p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n')
dump(CON/'argument_contract.json',contract)
md=['# Contrato do argumento\n',f"**ID:** `{contract['contract_id']}`  \n**PDF SHA-256:** `{sha(pdf)}`  \n**Fonte SHA-256:** `{sha(rmd)}`\n",'## 1. Source-bound identity\n','Artefato local completo; não há recibo com hash do upload ao Refine. Trechos do parecer correspondem materialmente ao PDF atual.\n','## 2. Document profile\n','Paper metodológico em inglês; 22 páginas; sete seções. Perfil general. Quatro agentes fizeram leituras delimitadas; foram reutilizados em turnos nas seções curtas, e não se reivindicam sete contextos independentes. O orquestrador leu o documento integralmente e os registros.\n','## 3. Thesis, question, and contribution\n',contract['synthesis']['thesis']+'\n',contract['synthesis']['contribution']+'\n','## 4. Core claims\n']
md += [f'### {c[0]}\n\n{c[1]}\n\nForça: {c[2]}.\n' for c in claims]
md += ['## 5. Claim → evidence → scope map\n','| Claim | Localizador | Evidência | Escopo |\n|---|---|---|---|']+[f'| {c[0]} | {c[3]} | {c[4]} | {c[5]} |' for c in claims]
md += ['\n## 6. Profile-specific contract\n','Método estatístico, sem jogo estratégico ou desenho empírico único. O contrato distingue os objetos listados no JSON e as duas aplicações.\n','## 7. What the document does not claim\n']+['- '+x for x in contract['synthesis']['non_claims']]
md += ['\n## 8. Terminology\n']+['- '+x['preferred']+': '+x['reason'] for x in contract['synthesis']['terminology']]
md += ['\n## 9. Reconciliation log\n']+[f'### {q}\n\n{a}\n' for q,a in reconciliations]
md += ['## 10. Gate verdict\n','**PASS de fidelidade no escopo de planejamento.** As tensões locais estão registradas, sem atribuir ao texto uma intenção de correção. O contrato não certifica a validade científica, a contribuição nem os outputs.\n']
(CON/'argument_contract.md').write_text('\n'.join(md))
(CON/'section_map.md').write_text('# Mapa de seções\n\n| Seção | Localizador | Leitor/turno | Função e dependência |\n|---|---|---|---|\n'+'\n'.join(f'| {i}. {s[0]} | {s[1]} | {s[2]} | {s[3]}; ver claims no contrato |' for i,s in enumerate(sections_raw,1))+'\n\nAs derivações que sustentam a Seção4 foram consultadas pelo leitor responsável e pelo macro; seus hashes estão no contrato.\n')

detail = [
 (1,'CONFIRMED','artifact','Rmd559-585','Referências a static audit e Task12/13 sem apêndices identificados no artigo.','','Apêndices devem ter identificação científica e parâmetros acessíveis.','safe','G4,G6'),
 (2,'PARTIAL','scope_or_consistency','Rmd194,650,736','A roadmap promete interação com baseline; nenhum caso estima o CET contemporâneo/ADL.','Os casos declaram explicitamente sua função descritiva e contraste não contemporâneo.','Corrigir promessa e criar aplicação central; não acusar resultados de fingirem identificação.','needs_design','G1,G5,G6'),
 (3,'PARTIAL','scope_or_consistency','Rmd141-150,646,777-799,822','Faltam tabela completa e universo explícito do maior ratio; três controles de Rogowski são adicionais.','A seção declara amostra intencional e não representativa.','Especificar universos de estudo, candidato e comparação extra.','safe','G0,G5'),
 (4,'PARTIAL','method','Rmd426-438; derivation uncertainty260-264','Apresentação principal não explicita independência entre unidades para reamostragem.','A nota reconhece dependência transversal e escopo unit-cluster restrito.','Trazer restrição ao corpo e validar para desenho escolhido; não reivindicar inferência geral.','needs_design','G3,G4'),
 (5,'PARTIAL','scope_or_consistency','Rmd222-238','Any responses coloca a mensuração depois de respostas que incluem Z; collider usa Y anterior a Z.','A própria seção explicita dois relógios distintos.','Distinguir outcome/processo e limitar a frase, sem afirmar que todo DAG está incoerente.','needs_design','G2'),
 (6,'PARTIAL','logic_or_proof','Rmd465; derivations/adl_cet_identification_conditions.Rmd63-73','Intercambialidade abreviada omite FE presentes na média potencial.','Nota formal inclui FE explicitamente e usa essa condição no passo1.','Reconciliar corpo e prova, não inventar uma falha global da derivação.','safe','G2'),
 (7,'CONFIRMED','scope_or_consistency','Rmd551; Figura4','Quatro modelos exibidos não incluem Z_t.','','Acrescentar comparação realmente aninhada com Z_t se sustentar claim, ou limitar figura.','needs_design','G4'),
 (8,'CONFIRMED','overclaim','Rmd583; metrics.R54-89; simulation.R70-111','O phase map compara viés de long com diferença entre endpoints e não separa Delta populacional de viés finito.','','Definir ambos os alvos e decompor componentes; coverage observada é de long contra CET.','needs_design','G2,G4'),
 (9,'PARTIAL','overclaim','Rmd315,441','Only the DAG e a passagem para efeito direto omitem hipóteses na frase local.','Seção3 exige hipóteses adicionais de mediação.','Aplicar os qualificadores junto à afirmação e verificar provas afetadas.','safe','G2,G6'),
 (10,'CONFIRMED','exposition','Rmd250-253','Regra otherwise só oferece plausible/ambiguous, omitindo pós-exposição documentada.','','Separar status temporal de papel causal.','safe','G2,G3'),
 (11,'CONFIRMED','scope_or_consistency','Rmd408-417,451,635-637','Moved e passos3-4 permitem leitura de substituição não coberta pelo produto único.','','Preservar lags na adição primária; derivar troca em passos identificados.','needs_design','G2,G3'),
 (12,'CONFIRMED','overclaim','Rmd619-625; Tabela6','1.023 e1.016 distam .007 e.014 do total1.03, e .023 e.016 do direto1.00.','','Corrigir near, apresentar incerteza e preservar targets originais.','safe','G4,G6'),
]
generals=[
 ('G1','PARTIAL','scope_or_consistency','Rmd184-192,389-444','Contribuição enfatiza nomear/estimar decomposição de ingredientes conhecidos.','O texto atribui identidade a FWL e reconhece escopo estreito.','Novidade incremental exige confronto integral com Gelbach e demonstração de decisão; não é possível prometer forte publicação.','G1,G4,G5'),
 ('G2','CONFIRMED','scope_or_consistency','Rmd451,629-637','Workflow não reconcilia substituição com adição aninhada.','','Corrigir contraste e provar decomposição da troca.','G2'),
 ('G3','PARTIAL','method','Rmd457-501,629-637','Condições de história são assumidas sem procedimento de seleção no corpo.','Baseline é expressamente condicional e nota possui prova de identificação.','Operacionalizar dentro de classe delimitada; AIC/BIC não prova suficiência causal.','G2,G3'),
 ('G4','PARTIAL','method','Rmd559-589','Artigo não integra DGPs completos e não diagnostica coverage mínima.','Equações/outputs existem em pacotes; 0.700 é CET de long, não IC Delta.','Integrar proveniência e desenhar avaliação correta de inferência.','G3,G4,G6'),
 ('G5','PARTIAL','scope_or_consistency','Rmd650,736','Aplicações não instanciam CET e inferência proposta.','O texto admite ambos os limites.','Selecionar aplicação por compatibilidade documental, não resultado.','G1,G5'),
]
original=(OUT/'evidence/refine_feedback_original.md').read_text()
import re
headings=dict((int(n),h) for n,h in re.findall(r'^### (\d+)\. (.*)$',original,re.M))
findings=[]
for n,status,typ,loc,defect,refute,reason,assessment,gates in detail:
 findings.append({'finding_id':f'R1-D{n:02}','source_review':'R1','quoted_finding':headings[n],'type':typ,'severity':'major' if n not in [3,10,12] else 'moderate','scientific_dimension':'inference' if n==4 else ('identification' if n in [2,5,6,9] else 'scope'),'held_decision':False,'status':status,'source_locations':[loc],'defect_evidence':[defect],'refuting_evidence':[refute] if refute else [],'mechanical_checks':['Inspeção do CSV e código sem reexecutar análise; origem de coverage confirmada.'] if n==8 else (['Distâncias aos dois alvos conferidas por aritmética.'] if n==12 else []),'reasoning':reason,'proposed_fix_assessment':assessment,'disposition':gates})
for n,status,typ,loc,defect,refute,reason,gates in generals:
 findings.append({'finding_id':f'R1-{n}','source_review':'R1','quoted_finding':'Comentário geral '+n,'type':typ,'severity':'major','scientific_dimension':'contribution' if n=='G1' else 'scope','held_decision':False,'status':status,'source_locations':[loc],'defect_evidence':[defect],'refuting_evidence':[refute] if refute else [],'mechanical_checks':[],'reasoning':reason,'proposed_fix_assessment':'needs_design','disposition':gates})
cf=CON/'argument_contract.json'
record={'schema_version':'1.0','adjudication_id':'ivb-pa-refine:5375d3c27ac1:round1','source':{'reviewed_artifact':str(pdf),'sha256':sha(pdf),'artifact_intact':True},'contract':{'required':True,'path':str(cf),'sha256':sha(cf),'contract_id':contract['contract_id'],'artifact_sha256':sha(pdf),'status':'PASS','stale':False},'review_sources':[{'review_id':'R1','path':str(OUT/'evidence/refine_feedback_original.md'),'sha256':sha(OUT/'evidence/refine_feedback_original.md')}],'findings':findings,'summary':{'total':len(findings),'confirmed':sum(x['status']=='CONFIRMED' for x in findings),'partial':sum(x['status']=='PARTIAL' for x in findings),'refuted':0,'unresolved':0,'held_decisions':0},'adjudication':{'verdict':'READY_FOR_IMPLEMENTATION','checked_at':now,'reasons':['Defeitos locais identificados para encaminhamento ao plano; soluções classificadas needs_design dependem dos gates correspondentes.','Veredicto técnico não autoriza execução nem certifica originalidade, eficácia futura ou publicação.','A previsão editorial da resposta complementar não é um finding verificável; quatro recomendações são mapeadas ao plano sem endossar certeza de êxito.']}}
dump(ADJ/'adjudication_round1.json',record)
md=['# Adjudicação do parecer Refine\n','## 1. Source and contract identity\n',f'PDF SHA-256: `{sha(pdf)}`. Contrato: `{contract["contract_id"]}`.\n','## 2. Executive disposition\n',f'{record["summary"]["confirmed"]} comentários confirmados e {record["summary"]["partial"]} parciais, somando cinco gerais e12 detalhados. As ressalvas presentes são preservadas; não se atribuem claims universais ao paper. As recomendações complementares sobre valor diagnóstico, aplicação, história e nesting seguem nos mesmos gates.\n','## 3. Findings table\n','| ID | Status | Localizador | Encaminhamento |\n|---|---|---|---|']
md += [f'| {f["finding_id"]} | {f["status"]} | {f["source_locations"][0]} | {f["disposition"]} |' for f in findings]
md += ['\n## 4. Evidence and reasoning by finding\n']
for f in findings:
 md += [f'### {f["finding_id"]}: {f["quoted_finding"]}\n',f'**{f["status"]}.** '+f['defect_evidence'][0]+'\n']
 if f['refuting_evidence']: md += ['Contrapeso: '+f['refuting_evidence'][0]+'\n']
 md += [f['reasoning']+f' Solução: `{f["proposed_fix_assessment"]}`. Gates: {f["disposition"]}.\n']
md += ['## 5. Unsafe fixes and owner decisions\n','Não inferir causalidade pelos componentes; não chamar seleção de lags de prova causal; não transformar o contraste de estoque de Rogowski em CET por mudança de índice. Mudança de rota científica após Gate1 exige decisão do autor.\n','## 6. Unresolved items\n','Não restam dúvidas sobre os defeitos locais para fins de planejar revisão. Originalidade incremental, aplicação adequada e inferência válida são objetivos prospectivos, não resultados certificados nesta adjudicação.\n','## 7. Adjudication verdict\n','**READY_FOR_IMPLEMENTATION** no sentido de encaminhar defeitos e desenhos aos gates. Este turno entrega planejamento; não implementa o paper.\n']
(ADJ/'adjudication_round1.md').write_text('\n'.join(md))
files=[pdf,rmd,ROOT/'README.md',ROOT/'CLAUDE.md',ROOT/'references.bib']+support[1:]+[ROOT/'derivations/scripts/specification_shift_uncertainty.R',ROOT/'simulations/finite_T_dynamic_panel/R/metrics.R',ROOT/'simulations/finite_T_dynamic_panel/R/simulation.R',ROOT/'quality_reports/task13_finite_T_dynamic_panel/task13_main_text_summary.csv',OUT/'evidence/refine_feedback_original.md']
dump(OUT/'evidence/source_manifest.json',{'generated_at':now,'base_commit':'482796295b843cc6d9c88c33b4ae5a714c005123','files':[{'path':str(p),'sha256':sha(p)} for p in files],'limits':['Uploaded bytes to Refine are not independently recorded.','Paper analyses were inspected but not executed.','No journal acceptance probability or original methodological contribution established.']})
print('Built source manifest, argument contract and adjudication; no paper calculations executed.')
