library(haven)
library(dplyr)

df <- read_dta("/Users/manoelgaldino/Documents/DCP/Papers/IVB/IVB-paper/replication/candidate_papers/burnside_dollar_2000/NDND.dta")

# Generate needed variables
df$bdlgdp <- log(df$bdgdp)
df$bdpolicy <- df$bddatap
df$bdoutlier <- df$bddatao
df$bdaidpolicy <- df$bdaid * df$bdpolicy
df$bdethnfassas <- df$bdethnf * df$bdassas

cat("================================================================\n")
cat("FINAL ASSESSMENT: BURNSIDE & DOLLAR (2000) FOR IVB ANALYSIS\n")
cat("================================================================\n\n")

cat("=== PAPER OVERVIEW ===\n")
cat("Title: Aid, Policies, and Growth\n")
cat("Authors: Craig Burnside & David Dollar\n")
cat("Journal: American Economic Review, 2000, 90(4), 847-868\n")
cat("Data: Panel of 56 developing countries, 6 four-year periods (1970-93)\n")
cat("Replication data: Easterly, Levine & Roodman extended dataset (1966-97)\n\n")

cat("=== SPECIFICATION (Table 4, Column 5/OLS) ===\n")
cat("Y: GDP per capita growth (bdgdpg)\n")
cat("D: Aid/GDP (bdaid) and Aid*Policy interaction (bdaidpolicy)\n")
cat("Controls:\n")
cat("  - bdlgdp: Log initial GDP per capita (CONTINUOUS, TIME-VARYING)\n")
cat("  - bdethnf: Ethnic fractionalization (CONTINUOUS, TIME-INVARIANT)\n")
cat("  - bdassas: Assassinations per million pop (CONTINUOUS, TIME-VARYING)\n")
cat("  - bdethnfassas: Ethnic frac * assassinations (CONTINUOUS, TIME-VARYING)\n")
cat("  - bdssa: Sub-Saharan Africa dummy (BINARY, TIME-INVARIANT)\n")
cat("  - bdeasia: East Asia dummy (BINARY, TIME-INVARIANT)\n")
cat("  - bdicrge: Institutional quality ICRG (CONTINUOUS, TIME-INVARIANT***)\n")
cat("  - bdm21: M2/GDP lagged (CONTINUOUS, TIME-VARYING)\n")
cat("  - bdpolicy: Policy index (CONTINUOUS, TIME-VARYING)\n")
cat("  - Period dummies (BINARY, time FE)\n\n")

cat("*** CRITICAL FINDING: bdicrge is TIME-INVARIANT in BD data.\n")
cat("    Same value repeated across all periods for each country.\n")
cat("    This means it is essentially a country-level covariate.\n\n")

cat("=== IVB REQUIREMENT CHECKLIST ===\n\n")

cat("1. LINEAR OLS REGRESSION: YES\n")
cat("   The main OLS specification is a standard linear regression.\n")
cat("   FWL theorem applies. No nonlinear link functions.\n\n")

cat("2. CONTINUOUS TIME-VARYING CONTROLS: PARTIALLY MET\n")
cat("   Time-varying continuous controls:\n")
cat("     - bdm21 (M2/GDP): within-country SD = 6.51, total SD = 13.28\n")
cat("     - bdpolicy (Policy index): within-country SD = 0.68, total SD = 1.26\n")
cat("     - bdlgdp (Log initial GDP): within-country SD = 0.17, total SD = 0.70\n")
cat("     - bdassas (Assassinations): within-country SD = 0.46, total SD = 1.24\n")
cat("   Time-invariant controls (not useful for IVB):\n")
cat("     - bdicrge (ICRG institutional quality): CONSTANT within country\n")
cat("     - bdethnf (Ethnic fractionalization): CONSTANT within country\n")
cat("     - bdssa, bdeasia (regional dummies): CONSTANT\n\n")

cat("3. SELECTION-ON-OBSERVABLES: YES (for OLS specs)\n")
cat("   The paper has OLS specifications (Table 4, cols 4-5, 7-8 OLS columns).\n")
cat("   These are pure cross-country growth regressions without country FE.\n")
cat("   Identification relies on controlling for observable confounders.\n\n")

cat("4. PLAUSIBLE COLLIDERS:\n\n")

cat("   BEST CANDIDATE: bdm21 (Financial depth, M2/GDP ratio)\n")
cat("   - Aid -> M2/GDP: YES. Aid inflows increase money supply,\n")
cat("     particularly when monetized by the central bank.\n")
cat("   - Growth -> M2/GDP: YES. Economic growth deepens financial\n")
cat("     markets; higher income leads to more banking/savings.\n")
cat("   - M2/GDP -> Growth: DEBATED. Standard in finance-growth\n")
cat("     literature (King & Levine 1993) but direction unclear.\n")
cat("   - Continuous, time-varying, sufficient variation.\n")
cat("   - VERDICT: GOOD collider candidate for IVB.\n\n")

cat("   SECOND CANDIDATE: bdpolicy (Policy index)\n")
cat("   - Aid -> Policy: YES. Conditionality, structural adjustment.\n")
cat("   - Growth -> Policy: YES. Growth generates fiscal space, stability.\n")
cat("   - Policy -> Growth: YES (paper's central claim).\n")
cat("   - COMPLICATION: Policy enters via the interaction aid*policy.\n")
cat("     Removing policy from regression also removes the interaction,\n")
cat("     which fundamentally changes the specification.\n")
cat("   - VERDICT: Conceptually interesting but COMPLICATED for IVB\n")
cat("     because it's intertwined with the treatment specification.\n\n")

cat("   WEAK CANDIDATE: bdassas (Assassinations)\n")
cat("   - Aid -> Assassinations: WEAK path.\n")
cat("   - Growth -> Assassinations: Plausible (instability channel).\n")
cat("   - Many zeros (sparse data). Only 47/71 countries have variation.\n")
cat("   - VERDICT: Weak but possible secondary collider.\n\n")

cat("   NOT VIABLE: bdicrge (Institutional quality)\n")
cat("   - TIME-INVARIANT in BD data. Cannot be a collider in the usual sense\n")
cat("     because it does not respond to contemporaneous aid or growth.\n")
cat("   - Acts like a country fixed effect.\n")
cat("   - VERDICT: NOT a useful collider for IVB.\n\n")

cat("=== RECOMMENDED SPECIFICATION FOR IVB ===\n\n")
cat("Use BD Table 4, Column 5/OLS (outliers excluded):\n")
cat("  Y = bdgdpg\n")
cat("  D = c('bdaid', 'bdaidpolicy')  [both treatment terms]\n")
cat("  Z = bdm21  [collider: financial depth]\n")
cat("  W = c('bdlgdp', 'bdethnf', 'bdassas', 'bdethnfassas',\n")
cat("        'bdssa', 'bdeasia', 'bdicrge', 'bdpolicy')  [remaining controls]\n")
cat("  FE = period dummies\n")
cat("  Sample: BD original sample, outliers excluded (N=270)\n\n")

cat("Alternative: Also test with bdpolicy as collider (removing interaction too).\n\n")

cat("=== OVERALL VERDICT: GOOD ===\n\n")
cat("Burnside & Dollar (2000) is a GOOD candidate for IVB analysis.\n\n")
cat("Strengths:\n")
cat("  1. Linear OLS, FWL applies cleanly\n")
cat("  2. Panel data with multiple time-varying continuous controls\n")
cat("  3. Clear selection-on-observables design (OLS specification)\n")
cat("  4. M2/GDP (bdm21) is a strong collider candidate:\n")
cat("     - Continuous and time-varying\n")
cat("     - Clear causal paths from both aid and growth\n")
cat("     - Its effect on growth is debated (not a clear-cut confounder)\n")
cat("  5. Highly influential paper (4000+ citations)\n")
cat("  6. Known fragility (Easterly, Levine & Roodman showed sensitivity)\n")
cat("  7. IVB could provide a NEW perspective on why the result is fragile:\n")
cat("     the included M2/GDP or policy variables may be colliders\n")
cat("  8. Data and code publicly available, replication confirmed\n\n")
cat("Concerns (manageable):\n")
cat("  1. Interaction term (aid*policy) requires careful IVB handling\n")
cat("     with multiple treatment terms d_vars = c('bdaid', 'bdaidpolicy')\n")
cat("  2. ICRGE is time-invariant (rules out one natural collider candidate)\n")
cat("  3. Some controls are confounders as well as potential colliders\n")
cat("  4. Small sample (N=270 with outliers excluded)\n")
