#!/usr/bin/env Rscript
# Static, non-Monte-Carlo inventory builder for Task 10.
# It only reads source files and existing result artifacts.

suppressPackageStartupMessages(library(data.table))

root <- normalizePath(".")
out_dir <- file.path(root, "quality_reports")
hash_file <- function(path) unname(tools::md5sum(path))
rel <- function(x) sub(paste0("^", root, "/"), "", normalizePath(x, mustWork = FALSE))

make_row <- function(id, family, script, results, equations, dag, estimand,
                     parameters, n, tt, burn, reps, errors, fe, models,
                     metrics, tags, notes = "", status = "verified_existing_artifacts") {
  script_abs <- file.path(root, script)
  result_abs <- file.path(root, strsplit(results, ";", fixed = TRUE)[[1]])
  result_abs <- result_abs[nzchar(result_abs)]
  result_abs <- result_abs[file.exists(result_abs)]
  data.table(
    inventory_id = id, simulation_family = family, source_script = script,
    source_script_md5 = if (file.exists(script_abs)) hash_file(script_abs) else NA_character_,
    result_file_paths = results,
    result_file_md5 = paste(vapply(result_abs, hash_file, character(1)), collapse = ";"),
    verification_basis = if (file.exists(script_abs) && length(result_abs))
      "directly verified: static source inspection plus existing versioned result artifact" else
      "directly verified source; result artifact absent or not linked",
    equations = equations, causal_dag_description = dag, estimand = estimand,
    parameter_values_or_grid = parameters, N = n, T = tt, burn_in = burn,
    repetitions = reps, error_process = errors, fixed_effects = fe,
    estimated_models = models, metrics = metrics, coverage_tags = tags,
    status = status, notes = notes,
    quantitative_claim_provenance = if (length(result_abs))
      paste0(script, " + ", results) else script
  )
}

rows <- list(
 make_row("v1_twfe", "v1 baseline FWL/TWFE grid", "simulations/v1_twfe/sim_ivb_twfe.R", "simulations/v1_twfe/sim_ivb_twfe_results.csv", "Y=beta D+unit FE+time FE+eps; Z=(gamma_D+gamma_Y beta)D+unit/time components+nu (as implemented).", "D->Y; D->Z<-Y contemporaneous collider.", "beta and FWL specification shift beta_long-beta_short.", "400 scenarios x 500 reps; gamma_Y, gamma_D, delta, within-R2 grid (see result CSV).", "source/result CSV", "source/result CSV", "none stated", "500 per scenario", "iid Gaussian innovations; generated unit/time components.", "unit and time FE in short, long, and auxiliary models.", "TWFE short Y~D; long Y~D+Z; auxiliary Z~D.", "bias, IVB/FWL identity, SE and stability fields in CSV.", "collider", "Result CSV is the authoritative parameter grid; legacy design described as tautological in repository instructions."),
 make_row("v1_legacy_completa", "v1 legacy exploratory bundle", "simulations/v1_twfe/sim_ivb_completa.R", "", "Multiple exploratory cross-section, grid, ADL, rho, and common-warm-up DGPs in one script; no single persisted output contract.", "Mixed; inspect source sections before reuse.", "varies by section.", "n=10,000 in early sections; later N=200,T=20, nsim=500; beta values 1 or 5.", "mixed", "mixed", "not stated", "500 in documented blocks", "iid Gaussian where shown.", "varies.", "varies.", "means/bias comparisons printed in-session.", "legacy", "No versioned CSV is written by this script; retained in inventory to prevent unsupported quantitative claims.", "legacy_no_persisted_result"),
 make_row("v4_mechA", "v4 mechanism A: between/within D-to-Z", "simulations/v4_mechanisms/sim_ivb_twfe_v4.R", "simulations/v4_mechanisms/results/sim_ivb_twfe_v4_mechA.csv", "Y=beta D+alpha_i+lambda_t+eps; Z=gamma_D_btw mu_i^D+gamma_D_wth(D-mu_i^D)+gamma_Y Y+eta_i+mu_t+nu.", "D->Y and D->Z<-Y; between D->Z channel absorbed by unit FE.", "beta and FWL shift.", "N=200,T=30,beta=1,reps=500; grid in source/result CSV.", "200", "30", "none", "500", "iid Gaussian eps,nu and FE components.", "unit and time FE.", "TWFE short/long and auxiliary Z~D.", "mean coefficients, bias, FWL components, SE.", "collider", "Directly verified from documented generator."),
 make_row("v4_mechB", "v4 mechanism B: between/within Y-to-Z", "simulations/v4_mechanisms/sim_ivb_twfe_v4.R", "simulations/v4_mechanisms/results/sim_ivb_twfe_v4_mechB.csv", "Y=beta D+alpha_i+lambda_t+eps; Z=gamma_D D+gamma_Y_btw Ybar_i+gamma_Y_wth(Y-Ybar_i)+eta_i+mu_t+nu.", "D->Y and D->Z<-Y; between Y component is absorbed by FE.", "beta and FWL shift.", "N=200,T=30,beta=1,reps=500; grid in source/result CSV.", "200", "30", "none", "500", "iid Gaussian.", "unit and time FE.", "TWFE short/long and auxiliary.", "mean coefficients, bias, FWL components, SE.", "collider", "Directly verified from documented generator."),
 make_row("v4_mechC", "v4 mechanism C: staggered binary treatment", "simulations/v4_mechanisms/sim_ivb_twfe_v4.R", "simulations/v4_mechanisms/results/sim_ivb_twfe_v4_mechC.csv", "D=1(t>=adoption) for switchers, 0 never, 1 always; Y=beta D+FE+eps; Z=gamma_D D+gamma_Y Y+FE+nu.", "D->Y and D->Z<-Y with absorbing staggered binary D.", "beta and FWL shift.", "N=200,T=30,beta=1,reps=500; switcher-probability grid in CSV.", "200", "30", "none", "500", "iid Gaussian outcome/control shocks.", "unit and time FE.", "TWFE short/long and auxiliary.", "bias, SE and FWL components.", "collider;staggered_binary_treatment", "This is distinct from the later dynamic staggered-posttreatment DGP."),
 make_row("v4_mechD", "v4 mechanism D: measurement error in Z", "simulations/v4_mechanisms/sim_ivb_twfe_v4.R", "simulations/v4_mechanisms/results/sim_ivb_twfe_v4_mechD.csv", "Baseline collider DGP with observed Z*=Z+measurement error (see source generator).", "D->Y and D->Z<-Y; observed control is measured with error.", "beta and attenuation of FWL shift.", "N=200,T=30,beta=1,reps=500; measurement-error grid in CSV.", "200", "30", "none", "500", "iid Gaussian structural and measurement errors.", "unit and time FE.", "TWFE short/long and auxiliary using observed Z.", "bias, FWL components, SE.", "collider;measurement_error", "Directly verified from source/result artifact."),
 make_row("mechC_adl", "dual-role / firewall ADL battery", "simulations/v4_mechanisms/sim_mechC_adl.R", "simulations/v4_mechanisms/results/sim_mechC_adl_results.csv;simulations/v4_mechanisms/results/sim_mechC_adl_raw.csv;simulations/v4_mechanisms/results/sim_mechC_adl_timing.csv", "Dynamic dual-role system with D,Y,Z lags; Z_t responds to D_t and Y_t and Z_{t-1} transmits prior confounding/collider structure.", "Z_{t-1}->D_t and Z_{t-1}->Y_t; D_t->Y_t; D_t->Z_t<-Y_t. Conditioning on Y_{t-1},Z_{t-1} is the tested firewall.", "direct beta=1 under the stated DGP.", "Grid documented in source and timing CSV; N_REPS=500.", "timing CSV", "timing CSV", "source parameters", "500", "iid Gaussian innovations.", "unit and time FE.", "8-model FE grid: TWFE; ADL with Y_lag, D_lag, Z_lag combinations.", "bias, RMSE/MC summaries and model comparisons.", "dual_role;firewall", "Parameter values are intentionally left to versioned timing CSV rather than transcribed from a mutable console."),
 make_row("dual_role_base", "dual-role Z baseline", "simulations/dual_role_z/sim_dual_role_z.R", "simulations/dual_role_z/results/sim_dual_role_z_results.csv;simulations/dual_role_z/results/sim_dual_role_z_raw.csv", "D=alpha_D+gamma_D Z_lag+rho_D D_lag+u; Y=alpha_Y+beta D+gamma_Y Z_lag+rho_Y Y_lag+e; Z=alpha_Z+delta_D D+delta_Y Y+rho_Z Z_lag+nu.", "Z_lag is a confounder; Z_t is collider D_t->Z_t<-Y_t.", "beta=1.", "N=100,T=30,burn=100,reps=200; rho_Z and sigma_alphaZ grid in result CSV.", "100", "30", "100", "200", "iid Gaussian innovations and Gaussian unit effects.", "unit and time FE where applicable.", "TWFE short/long; ADL short/long.", "bias and MCSE by model.", "dual_role", "Directly verified source and CSV."),
 make_row("dual_role_8models", "dual-role Z full 2x2x2 estimator grid", "simulations/dual_role_z/sim_dual_role_z_8models.R", "simulations/dual_role_z/results/sim_dual_role_z_8models_results.csv;simulations/dual_role_z/results/sim_dual_role_z_8models_raw.csv", "D=alpha_D+gamma_D Z_lag+rho_D D_lag+u; Y=alpha_Y+beta D+gamma_Y Z_lag+rho_Y Y_lag+e; Z=alpha_Z+delta_D D+delta_Y Y+rho_Z Z_lag+nu.", "Z_lag confounder and Z_t collider; contrasts FE/no-FE, lag inclusion/exclusion.", "beta=1.", "N=100,T=30,burn=100,reps=500; rho_Z={.1,.3,.5,.7,.85}; sigma_alphaZ={.5,2}.", "100", "30", "100", "500", "iid Gaussian innovations/unit effects.", "unit/time FE in FE estimators.", "Pooled short/long; TWFE short/long; ADL short/long with and without FE.", "bias, SD, MCSE.", "dual_role;firewall", "Equation and all stated values are source comments/parameters."),
 make_row("dual_role_asymmetry", "dual-role causal-channel asymmetry", "simulations/dual_role_z/sim_dual_role_z_asymmetry.R", "simulations/dual_role_z/results/sim_dual_role_z_asymmetry_results.csv", "Same dynamic dual-role equations; varies D->Z and Y->Z channel strengths.", "Z_lag confounder; Z_t collider.", "beta=1.", "N/T/burn and grid directly in source; reps=500.", "source", "source", "source", "500", "iid Gaussian.", "unit/time FE.", "TWFE and ADL short/long.", "bias and net TWFE/ADL contrasts.", "dual_role", "Use source for exact grid; no raw artifact listed."),
 make_row("dual_role_firewall", "dual-role firewall sensitivity", "simulations/dual_role_z/sim_dual_role_z_firewall.R", "simulations/dual_role_z/results/sim_dual_role_z_firewall_results.csv", "Same dynamic dual-role equations; varies outcome persistence to test whether Y_lag blocks inherited paths.", "Dual-role Z with firewall through observed history.", "beta=1.", "Source grid; reps=500; rho_Y includes 0,.5,.8.", "source", "source", "source", "500", "iid Gaussian.", "unit/time FE.", "TWFE and ADL short/long.", "bias and firewall comparisons.", "dual_role;firewall", "Exact N/T values are source-verified but reported as source to avoid duplicating a parameter table."),
 make_row("dual_role_varyT", "dual-role finite-T variation", "simulations/dual_role_z/sim_dual_role_z_varyT.R", "", "Same dynamic dual-role equations; varies T.", "Dual-role Z with lagged confounding/current collider.", "beta=1.", "Source grid varies T and rho_Z; reps=200.", "source", "varies", "source", "200", "iid Gaussian.", "unit/time FE.", "TWFE and ADL short/long.", "bias by T.", "dual_role;firewall", "The script declares an output path, but no matching versioned result artifact exists in the audited tree; it cannot support a numerical claim.", "declared_output_missing"),
 make_row("dual_role_varyT_8models", "dual-role finite-T full estimator grid", "simulations/dual_role_z/sim_dual_role_z_varyT_8models.R", "simulations/dual_role_z/results/sim_dual_role_z_varyT_8models_results.csv", "Same dynamic dual-role equations; varies T under eight estimators.", "Dual-role Z with lagged confounding/current collider.", "beta=1.", "Source grid varies T and rho_Z; reps=500.", "source", "varies", "source", "500", "iid Gaussian.", "unit/time FE in FE models.", "Pooled/TWFE/ADL 2x2x2 grid.", "bias, SD, MCSE by T.", "dual_role;firewall", "Summary-only artifact; raw results absent."),
 make_row("nl_collider", "nonlinear collider / firewall", "simulations/nonlinearity/sim_nl_collider.R", "simulations/nonlinearity/results/sim_nl_collider_results.csv;simulations/nonlinearity/results/sim_nl_collider_raw.csv;simulations/nonlinearity/results/sim_nl_collider_timing.csv", "Dynamic dual-role DGP with nonlinear D->Z and/or Y->Z functions (log2, log4, softpoly2, power1.5, sin, invlogit, tanh, Dlog, Y2).", "Lagged Z confounder/current Z collider under nonlinear channels.", "beta=1.", "N_REPS=500; T={10,30}; exact nonlinear grid in timing CSV.", "timing CSV", "10;30", "source", "500", "iid Gaussian innovations; unstable draws handled in source.", "unit/time FE.", "TWFE and ADL variants via shared estimator utility.", "bias, RMSE, MCSE and timing.", "nonlinearity;firewall", "Directly verified; numerical ranges preserved in versioned timing/results CSVs."),
 make_row("nl_interact", "nonlinear D-by-history interaction", "simulations/nonlinearity/sim_nl_interact.R", "simulations/nonlinearity/results/sim_nl_interact_results.csv;simulations/nonlinearity/results/sim_nl_interact_raw.csv;simulations/nonlinearity/results/sim_nl_interact_timing.csv", "Dynamic dual-role DGP with interaction term delta_DH (see source) in Z process.", "Lagged Z confounder/current collider, nonlinear interaction.", "beta=1.", "N_REPS=500; grid delta_DH and rho_Z in timing CSV.", "timing CSV", "source", "source", "500", "iid Gaussian.", "unit/time FE.", "TWFE and ADL variants.", "bias, RMSE, MCSE.", "nonlinearity;firewall", "Equation shorthand; source is controlling specification."),
 make_row("nl_carryover", "nonlinear carryover", "simulations/nonlinearity/sim_nl_carryover.R", "simulations/nonlinearity/results/sim_nl_carryover_results.csv;simulations/nonlinearity/results/sim_nl_carryover_raw.csv;simulations/nonlinearity/results/sim_nl_carryover_timing.csv", "Dynamic dual-role DGP with nonlinear carryover beta_nl and k applied to treatment history.", "Lagged dynamics with collider structure.", "direct beta=1 and model-specific estimands under carryover.", "N_REPS=500; k={0,.05,.1,.25,.5,1}; rho_Z={.5,.7}; raw/softclamp variants.", "timing CSV", "source", "source", "500", "iid Gaussian.", "unit/time FE.", "TWFE and ADL variants.", "bias, RMSE, MCSE, timing.", "nonlinearity;carryover;firewall", "Total-effect interpretation under nonlinear carryover must follow source definitions."),
 make_row("overcontrol_contemp", "contemporaneous pure-mediator over-control", "simulations/nonlinearity/sim_overcontrol_contemporaneous.R", "simulations/nonlinearity/results/sim_overcontrol_contemporaneous_results.csv;simulations/nonlinearity/results/sim_overcontrol_contemporaneous_raw.csv;simulations/nonlinearity/results/sim_overcontrol_contemporaneous_timing.csv", "D=alpha_D+rho_D D_lag+u; Z=alpha_Z+f(D)+rho_Z Z_lag+nu; Y=alpha_Y+beta D+theta Z+rho_Y Y_lag+e.", "D_t->Z_t->Y_t mediator; explicitly no Y_t->Z_t.", "direct beta=1; linear total effect beta+theta delta_D.", "N=100,T=30,burn=100,reps default 500; theta=.5,delta_D=.4,rho_D=rho_Y=.5; nonlinear grid in source.", "100", "30", "100", "500 default (environment override)", "iid Gaussian; pilot only calibrates scale, not a Monte Carlo result.", "unit/time FE.", "TWFE, ADL with D/Y lags and contemporaneous or lagged Z.", "bias relative to direct/linear total targets; FWL difference.", "mediator_overcontrol;nonlinearity", "Static source declares an environment override; execution metadata should be consulted for actual reps."),
 make_row("direct_carryover", "linear direct carryover", "simulations/dynamics/sim_direct_carryover.R", "simulations/dynamics/results/sim_direct_carryover_results.csv;simulations/dynamics/results/sim_direct_carryover_raw.csv;simulations/dynamics/results/sim_direct_carryover_timing.csv", "Dynamic dual-role DGP with Y_t including beta D_t+beta2 D_lag plus lagged Y/Z.", "Lagged Z confounder/current collider plus direct treatment carryover.", "contemporaneous beta=1; models may target misspecified effects when omitting D_lag.", "N_REPS=500; beta2 and rho_Z grid in timing CSV.", "timing CSV", "source", "source", "500", "iid Gaussian.", "unit/time FE.", "8-model TWFE/ADL grid.", "bias, RMSE, MCSE, timing.", "carryover;firewall", "Do not call every coefficient bias to beta when the omitted carryover changes the estimand."),
 make_row("direct_feedback", "lagged outcome-to-treatment feedback", "simulations/dynamics/sim_direct_feedback.R", "simulations/dynamics/results/sim_direct_feedback_results.csv;simulations/dynamics/results/sim_direct_feedback_raw.csv;simulations/dynamics/results/sim_direct_feedback_timing.csv", "Dynamic dual-role DGP with D_t including phi Y_lag.", "Y_{t-1}->D_t feedback; lagged Z confounding/current collider.", "beta=1 under stated history adjustment.", "N_REPS=500; phi and rho_Z grid in timing CSV.", "timing CSV", "source", "source", "500", "iid Gaussian.", "unit/time FE.", "TWFE and ADL variants.", "bias, MCSE, timing.", "feedback;firewall", "Lagged feedback is not contemporaneous feedback."),
 make_row("feedback_Y_to_D", "feedback Y_lag to D with extended ADL", "simulations/dynamics/sim_feedback_Y_to_D.R", "simulations/dynamics/results/sim_feedback_Y_to_D_results.csv;simulations/dynamics/results/sim_feedback_Y_to_D_raw.csv;simulations/dynamics/results/sim_feedback_Y_to_D_timing.csv", "D_t includes phi Y_lag; Y and Z follow dynamic dual-role equations.", "Y_lag->D_t and D_t->Z_t<-Y_t; Z_lag affects D,Y.", "beta=1 conditional on recorded history.", "N_REPS=500; stability-screened grid in timing CSV.", "timing CSV", "source", "source", "500", "iid Gaussian; unstable parameter sets flagged.", "unit/time FE.", "8-model TWFE/ADL grid plus auxiliary.", "bias, RMSE/MCSE, stability/timing.", "feedback;firewall", "Directly verified source/results."),
 make_row("feedback_carryover", "combined feedback and carryover", "simulations/dynamics/sim_feedback_carryover.R", "simulations/dynamics/results/sim_feedback_carryover_results.csv;simulations/dynamics/results/sim_feedback_carryover_raw.csv;simulations/dynamics/results/sim_feedback_carryover_timing.csv", "D_t includes phi Y_lag; Y_t includes beta D_t+beta2 D_lag with dynamic Z.", "Lagged feedback and carryover within dual-role structure.", "beta=1; misspecified models can target composite effects.", "N_REPS=500; phi,beta2,rho_Z grid in timing CSV.", "timing CSV", "source", "source", "500", "iid Gaussian.", "unit/time FE.", "8-model TWFE/ADL grid.", "bias, RMSE, ranking, timing.", "feedback;carryover;firewall", "Interpretation explicitly depends on included treatment lags."),
 make_row("persistent_unobserved", "persistent contemporaneous unobserved confounding", "simulations/dynamics/sim_persistent_confounder.R", "simulations/dynamics/results/sim_persistent_confounder_results.csv;simulations/dynamics/results/sim_persistent_confounder_raw.csv;simulations/dynamics/results/sim_persistent_confounder_timing.csv", "U_t=phi_U U_lag+v; D_t=...+kappa U_t+u; Y_t=...+delta_U U_t+e; Z_t=...+delta_D D_t+delta_Y Y_t+...+nu.", "U_t->D_t and U_t->Y_t contemporaneous confounding, alongside dual-role Z.", "beta=1; oracle models condition on U.", "N_REPS=500; 36 scenarios with kappa,phi_U,rho_Z,delta_U grids documented in source.", "timing CSV", "source", "source", "500", "iid Gaussian AR(1) U and iid other innovations.", "unit/time FE.", "standard 9-model battery + oracle U models + lag-ID sensitivity models.", "bias/MCSE; oracle contrast; discarded draws/timing.", "contemporaneous_unobserved_confounding;firewall", "A known limitation: ADL cannot remove U_t confounding without observing U or a design."),
 make_row("callaway_controls", "Callaway-style nonlinear control relationship and level-dependent trends", "simulations/dynamics/sim_callaway_controls.R", "simulations/dynamics/results/sim_callaway_controls_results.csv;simulations/dynamics/results/sim_callaway_controls_raw.csv;simulations/dynamics/results/sim_callaway_controls_timing.csv", "A: Y includes gamma_nl g(Z_lag); B: Y includes lambda H_i(t/T), Z includes delta_H H_i; D/Z remain dynamic dual-role.", "Functional-form or level-dependent-trend misspecification; collider on/off via delta_Y.", "beta=1 under stated DGP; diagnostic of specification robustness.", "56 scenarios x 500 reps; NL types softpoly2,power1.5,quadratic; exact grid in timing CSV.", "timing CSV", "source", "source", "500", "iid Gaussian innovations; H_i~N(0,1).", "unit/time FE (which do not absorb H_i x time).", "shared TWFE/ADL model battery.", "bias, RMSE/MCSE, discarded draws, timing.", "callaway_style_trends;nonlinearity;firewall", "Direct source comment distinguishes this from a collider mechanism."),
 make_row("staggered_posttreat", "absorbing staggered treatment with post-treatment lag", "simulations/dynamics/sim_staggered_posttreat.R", "simulations/dynamics/results/sim_staggered_posttreat_results.csv;simulations/dynamics/results/sim_staggered_posttreat_raw.csv;simulations/dynamics/results/sim_staggered_posttreat_timing.csv", "D is absorbing after random adoption for treated units; dynamic Y,Z system includes lagged outcome, so Y_lag may be post-treatment.", "Staggered binary D; D history affects Y_lag, and dual-role Z may be collider on/off.", "beta=1 contemporaneous structural coefficient, not necessarily a generic event-study ATT.", "N_REPS=500; prob_never,rho_Y,delta_Y,rho_Z grid in timing CSV.", "timing CSV", "source", "source", "500", "iid Gaussian innovations plus binary treatment assignment/adoption.", "unit/time FE.", "shared TWFE/ADL battery.", "bias, RMSE/MCSE, discarded draws/timing.", "staggered_binary_treatment;posttreatment_lag;firewall", "This is the dynamic-staggered design relevant to lagged-outcome adjustment."),
 make_row("jensen_twoperiod", "Jensen-calibrated two-period DiD", "simulations/dynamics/sim_jensen_two_period.R", "simulations/dynamics/results/sim_jensen_two_period_summary.csv;simulations/dynamics/results/sim_jensen_two_period_raw.csv;simulations/dynamics/results/sim_jensen_two_period_decomp.csv;simulations/dynamics/results/sim_jensen_two_period_scenarios.csv", "Binary D determined by X,V; post controls Zm (mediator-like) and Zc (collider-like) and post shock U enter the two-period potential-outcome design.", "D->Zm->Y; D->Zc<-U->Y; baseline X,V affect D and trends.", "ATT_total=tau_direct+y_zm*zm_d+y_zc*zc_d.", "Defaults: n=5,000,reps=500,seed=20260323; three scenario parameter sets in scenarios CSV.", "5,000 default", "2", "not applicable", "500 default (CLI override)", "Gaussian shocks; Bernoulli V,D from logistic probabilities.", "unit FE; no time FE in documented models.", "DiD baseline, TVC, safe pre-treatment interaction, full model.", "coefficient shifts, error against ATT_total, decomposition summaries.", "mediator_overcontrol;contemporaneous_unobserved_confounding", "User-supplied CLI options mean actual execution should be established from saved scenario/result metadata."),
 make_row("overcontrol_full", "mediator over-control with nonlinear D-to-Z", "simulations/overcontrol/sim_overcontrol.R", "simulations/overcontrol/results/sim_overcontrol_results.csv;simulations/overcontrol/results/sim_overcontrol_raw.csv;simulations/overcontrol/results/sim_overcontrol_grid.csv", "D=alpha_D+gamma_D Z_lag+rho_D D_lag+u; Z=alpha_Z+delta_D D+f_nl(D)+rho_Z Z_lag+nu; Y=alpha_Y+beta D+theta Z+gamma_Y Z_lag+rho_Y Y_lag+e.", "D_t->Z_t->Y_t mediator; optional Z_lag confounding; no Y_t->Z_t.", "linear total=beta+theta delta_D; direct=beta; nonlinear total is model-specific.", "N=100,T=30,burn=100,reps=500; 2 variants x 9 NL states x rho_Z {.5,.7}; grid CSV.", "100", "30", "100", "500", "iid Gaussian; pilot scale calibration.", "unit/time FE.", "10 TWFE/ADL models with contemporaneous vs lagged Z.", "bias, RMSE, FWL shift, grid/console diagnostics.", "mediator_overcontrol;nonlinearity", "Grid CSV is preserved as a first-class raw design artifact."),
 make_row("diag_heterogeneous", "diagnostic: heterogeneous treatment effects", "simulations/diagnostics/diag_heterogeneous.R", "simulations/diagnostics/results/diag_heterogeneous_results.csv", "Dynamic dual-role base DGP with beta_i heterogeneity controlled by sigma_beta.", "Dual-role dynamics with heterogeneous causal effect.", "mean beta / estimator target under heterogeneity.", "reps=200; sigma_beta={0,.3,.5,1}; base/extended scenario.", "source", "source", "source", "200", "iid Gaussian.", "unit/time FE in FE models.", "FE-ADL, extended FE-ADL, TWFE.", "bias summaries.", "heterogeneity;dual_role", "Diagnostic artifact, not a main planned DGP."),
 make_row("diag_ivb_sign", "diagnostic: IVB sign", "simulations/diagnostics/diag_ivb_sign.R", "simulations/diagnostics/results/diag_ivb_sign_results.csv", "Dynamic dual-role base DGP varying gamma_D and delta_Y.", "Lagged confounding/current collider.", "beta=1 and sign of specification shift.", "reps=200; gamma_D={0,.05,.15,.30}; other grid in source.", "source", "source", "source", "200", "iid Gaussian.", "unit/time FE.", "TWFE/ADL short/long.", "bias and sign tables.", "dual_role", "Diagnostic artifact."),
 make_row("diag_phi", "diagnostic: feedback mechanism", "simulations/diagnostics/diag_phi_bias_mechanism.R", "simulations/diagnostics/results/diag_phi_bias_mechanism_results.csv", "Dynamic system varying D_t response phi Y_lag.", "Lagged feedback in dual-role dynamics.", "beta=1 conditional on history.", "reps=300; phi={0,.05,.10,.15}; rho_Y={0,.5}.", "source", "source", "source", "300", "iid Gaussian.", "unit/time FE for FE model.", "FE ADL, no-FE ADL, D~Y_lag auxiliary.", "bias and R2 diagnostics.", "feedback", "Diagnostic artifact."),
 make_row("diag_sensitivity", "diagnostic: parameter sensitivity", "simulations/diagnostics/diag_sensitivity_params.R", "simulations/diagnostics/results/diag_sensitivity_params_results.csv", "Dynamic dual-role DGP varying rho_Y,gamma_D,gamma_Y and stability.", "Lagged confounding/current collider.", "beta=1.", "reps=200; rho_Y={.3,.5,.7}; stable subset only.", "source", "source", "source", "200", "iid Gaussian.", "unit/time FE.", "FE ADL variants.", "bias and stability summaries.", "dual_role;firewall", "Rows flagged unstable are excluded by source logic; see source/result."),
 make_row("diag_shortT", "diagnostic: short-T / Nickell", "simulations/diagnostics/diag_short_T.R", "simulations/diagnostics/results/diag_short_T_results.csv", "Dynamic dual-role DGP comparing T=10 and 30.", "Lagged confounding/current collider.", "beta=1; finite-T estimator behavior.", "reps=200; T={10,30}; scenarios in source.", "source", "10;30", "source", "200", "iid Gaussian.", "unit/time FE where specified.", "TWFE long; FE ADL; no-FE ADL.", "bias and Nickell-cost comparison.", "dual_role;firewall", "Diagnostic artifact."),
 make_row("diag_timeFE", "diagnostic: time FE in DGP", "simulations/diagnostics/diag_time_fe_in_dgp.R", "simulations/diagnostics/results/diag_time_fe_results.csv", "Dynamic dual-role DGP with time-shock variance sigma_delta.", "Dual-role dynamics plus common time shocks.", "beta=1.", "reps=200; sigma_delta={0,.3,.5,1}; scenarios in source.", "source", "source", "source", "200", "iid Gaussian time shocks and innovations.", "unit/time FE.", "TWFE and FE-ADL variants.", "bias summaries.", "dual_role;time_effects", "Diagnostic artifact.")
)

inventory <- rbindlist(rows, fill = TRUE)
setorder(inventory, inventory_id)

# Static validations: paths/hash existence, required columns, and numeric sanity in
# timing/grid/result CSVs. This intentionally never sources simulation scripts.
required <- c("inventory_id", "source_script", "equations", "causal_dag_description",
  "estimand", "parameter_values_or_grid", "N", "T", "burn_in", "repetitions",
  "error_process", "fixed_effects", "estimated_models", "metrics", "result_file_paths", "status")
stopifnot(identical(required, intersect(required, names(inventory))))
stopifnot(!anyDuplicated(inventory$inventory_id))
stopifnot(all(file.exists(file.path(root, inventory$source_script))))

artifact_rows <- inventory[nzchar(result_file_paths)]
artifact_paths <- unique(unlist(strsplit(artifact_rows$result_file_paths, ";", fixed = TRUE)))
artifact_paths <- artifact_paths[nzchar(artifact_paths)]
missing_artifacts <- artifact_paths[!file.exists(file.path(root, artifact_paths))]
if (length(missing_artifacts)) stop("Missing declared artifacts: ", paste(missing_artifacts, collapse = "; "))

manifest <- rbindlist(lapply(artifact_paths, function(p) {
  x <- file.path(root, p)
  hdr <- if (grepl("\\.csv$", p)) names(fread(x, nrows = 0)) else character()
  checks <- list()
  if (length(hdr)) {
    bounded <- intersect(hdr, c("rho_Z", "rho_Y", "rho_D", "phi", "phi_U", "prob_never", "T_start_frac", "T_end_frac", "R2_within"))
    positive_counts <- intersect(hdr, c("N", "TT", "T", "T_burn", "N_REPS", "n_sims", "n_valid", "sim"))
    nonnegative_counts <- intersect(hdr, c("n_discarded"))
    dates <- hdr[grepl("date", hdr, ignore.case = TRUE)]
    use <- unique(c(bounded, positive_counts, nonnegative_counts, dates))
    if (length(use)) {
      d <- fread(x, select = use, showProgress = FALSE)
      for (nm in bounded) {
        z <- d[[nm]]
        if (is.numeric(z) && any(!is.na(z) & (z < 0 | z > 1))) checks[[length(checks) + 1L]] <- paste0(nm, " outside [0,1]")
      }
      for (nm in positive_counts) {
        z <- d[[nm]]
        if (is.numeric(z) && any(!is.na(z) & z <= 0)) checks[[length(checks) + 1L]] <- paste0(nm, " is non-positive")
      }
      for (nm in nonnegative_counts) {
        z <- d[[nm]]
        if (is.numeric(z) && any(!is.na(z) & z < 0)) checks[[length(checks) + 1L]] <- paste0(nm, " is negative")
      }
      for (nm in dates) {
        z <- as.Date(d[[nm]])
        if (any(is.na(z) & !is.na(d[[nm]])) || any(z > as.Date("2026-07-11"), na.rm = TRUE)) checks[[length(checks) + 1L]] <- paste0(nm, " is invalid or after audit date")
      }
    }
  }
  data.table(path = p, md5 = hash_file(x), bytes = file.info(x)$size,
             csv_header = if (length(hdr)) paste(hdr, collapse = "|") else NA_character_,
             static_validation = if (length(checks)) paste(checks, collapse = "; ") else "PASS")
}))
fwrite(inventory, file.path(out_dir, "simulation_design_inventory.csv"))
fwrite(manifest, file.path(out_dir, "simulation_design_inventory_manifest.csv"))
fwrite(manifest[, .(path, static_validation)], file.path(out_dir, "simulation_design_inventory_validation.csv"))

cat(sprintf("Wrote %d inventory rows and %d artifact-manifest rows.\n", nrow(inventory), nrow(manifest)))
